### ISSUE TITLE
Request to provide output markdown file 

### ISSUE THREAD

**Issue by PavanMudigondaTR** [platisd/duplicate-code-detection-tool#10]
@platisd 

Is it possible for your to provide output markdown file which i can use for publishing as checkrun using another Github Action. Or alternatevely if you can publish the same markdown table as checkrun thats is also good enough for me.

**Comment by platisd** [comment]
I've been trying to [set an `output`](https://github.com/platisd/duplicate-code-detection-tool/tree/write_markdown_to_workspace) using GitHub Actions but to no avail so far. I am clearly doing it wrong. If you are more experienced with this, feel free to make the change and submit a pull request.

**Comment by irongut** [comment]
> I've been trying to [set an `output`](https://github.com/platisd/duplicate-code-detection-tool/tree/write_markdown_to_workspace) using GitHub Actions but to no avail so far. I am clearly doing it wrong. If you are more experienced with this, feel free to make the change and submit a pull request.

If your Action writes a file to the runner's file system other Actions can access it to process / post / whatever, no need to set an output. I do this in one of my Actions (not Python unfortunately or I'd try to help).

**Comment by platisd** [comment]
Ah, I wonder how nicely does this play with this action doing a `git pull` of its own internally. :thinking: 
I probably should change that anyway at some point and use [@actions/checkout](https://github.com/actions/checkout) instead. :cry: 

I'll give it a try later today. Thanks @irongut.

**Comment by irongut** [comment]
I don't think pull should affect it, especially if the pull is before the output, but its not something I've tried. Provided you don't commit anything back to the repo the file will just be temporary in the runner's file system.

**Comment by platisd** [comment]
@PavanMudigondaTR would [this](https://github.com/platisd/duplicate-code-detection-tool/pull/15) work for you?

It should write a `message.md` file with the same content posted as a comment.

**Comment by PavanMudigondaTR** [comment]
Yes. This is good enough. Thank you so much !
