### ISSUE TITLE
--ignore-directories option does work on gitbash (Windows)

### ISSUE THREAD

**Issue by Cael35** [platisd/duplicate-code-detection-tool#23]
Hello,
I'm using:
`> duplicate_code_detection.py --ignore-directories general/util/async/file/test -d general`
in gitbash terminal on Windows, but the files in general/util/async/file/test are not ignored.

Value example of involved variables:
```
ignore_directories = ['general/util/async/file/test']
files_to_ignore = ['general/util/async/file/test\\util_async_file_test\\File_test.cpp', ...]
source_code_files = [..., 'general\\util\\async\\file\\test\\util_async_file_test\\File_test.cpp',...]
```

I fixed it, do you want me to submit a PR ? :-)

**Comment by platisd** [comment]
Please feel free to submit a PR :+1:
