### ISSUE TITLE
No module named 'gensim'

### ISSUE THREAD

**Issue by nhjclxc** [platisd/duplicate-code-detection-tool#29]
![image](https://github.com/platisd/duplicate-code-detection-tool/assets/66449475/00af459b-83d0-489a-9088-176f499a1483)

>python duplicate_code_detection.py -d smartcar_shield/src
Traceback (most recent call last):
  File "E:\nbu\similar\code\duplicate-code-detection-tool\duplicate_code_detection.py", line 10, in <module>
    import gensim
ModuleNotFoundError: No module named 'gensim'

**Comment by platisd** [comment]
Have you installed the [dependencies](https://github.com/platisd/duplicate-code-detection-tool#dependencies), manually or via `pip install --user -r requirements.txt && python3 -m nltk.downloader punkt`?

**Comment by nhjclxc** [comment]
I opened the project with pycharm and used it to install all the dependencies, and then I tried the pip installation. Just ask if duplicate-code-detection-tool supports similarity detection at the java method level

**Comment by platisd** [comment]
> similarity detection at the java method level

No, it compares at the file-level.

**Comment by nhjclxc** [comment]
But now a new problem has arisen. When I executed "python3 -m nltk.downloader punkt", the following error occurred:
  Resource punkt not found.
   Please use the NLTK Downloader to obtain the resource:

   >>> import nltk
   >>> nltk.download('punkt')

   For more information see: https://www.nltk.org/data.html

   Attempted to load tokenizers/punkt/english.pickle

![image](https://github.com/platisd/duplicate-code-detection-tool/assets/66449475/fc8fd186-0b2c-417e-b626-adbe93db9f3a)

**Comment by nhjclxc** [comment]
Thanks for your guidance, I successfully ran the project

![image](https://github.com/platisd/duplicate-code-detection-tool/assets/66449475/22519190-3790-4b44-b122-3ae9c66bf7e4)

**Comment by platisd** [comment]
OK looks good, well done. I guess this issue can be closed  :+1:
