### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by i-salameh95** [platisd/duplicate-code-detection-tool#30]
I dont know how to use it, I have django project run by docker on my local development, and I need to run this tool within it, How ?

**Comment by platisd** [comment]
Hi, which part of the [instructions](https://github.com/platisd/duplicate-code-detection-tool?tab=readme-ov-file#example) are you not able to follow?
What have you tried so far?

**Comment by i-salameh95** [comment]
Sure, I have download the package, and then I download the prerequisite pip packages, and then I follow the instructions, it shows output for my project, but there are no numbers like the screenshots here, I will attach screenshot of what I mean

**Comment by i-salameh95** [comment]
![11111](https://github.com/platisd/duplicate-code-detection-tool/assets/78903915/ae2df2d4-4b49-4e0a-b728-7af7544c3ed9)
![22222](https://github.com/platisd/duplicate-code-detection-tool/assets/78903915/a9e9e002-954f-4cd0-8764-b52a058c074d)

what this output suppose to mean ?

**Comment by platisd** [comment]
My guess is you should try a different terminal,  not the default Windows one.

**Comment by i-salameh95** [comment]
if you could recommend specific one, I will be so thankful to u ! ..

**Comment by platisd** [comment]
Try `PowerShell` (probably already installed) or `bash` (you can get it when installing `git`)

**Comment by i-salameh95** [comment]
the same output appear on PowerShell, but my question here that: if there is an issue with specific file - contains duplicated code- the package should show something specific ? or it only shows a number colored red?

**Comment by i-salameh95** [comment]
Thanks, I have tried both of them, but PowerShell is the same like CMD, git bash is perfect.. 
I have another question: if a file after check it by this package shows 20.59 similarity with red color, then I should change the content of this file or what ? because this file doesn't contain duplicate code.. its my settings !! base.py file

**Comment by platisd** [comment]
>  then I should change the content of this file or what

This is up to you to decide by looking at the file's actual contents and compare them to the files the tool thinks are "similar". Sometimes it makes sense to refactor but that's not always the case.
