### ISSUE TITLE
be suitable for code similarity check?

### ISSUE THREAD

**Issue by schunlee** [platisd/duplicate-code-detection-tool#31]
from the source code, I see gensim be used here. gensim be used as text similarity check is cool, but whether be suitable to code similarity check?  I mean, for example I want to compare two Unity projects, all scripts must follow C# syntax, many C# fixed words, and to use Unity Engine, all same framework sentences be used such as 'using UnityEngine'. Can gensim ignore these? no mis-check?

**Comment by platisd** [comment]
> all same framework sentences be used such as 'using UnityEngine'. Can gensim ignore these?

As you mention, `gensim` isn't specialized to code and therefore won't be able to recognize common/utility syntax, e.g. `using UnityEngine`. That being said, if your files are large enough such common parts should not make a big difference.

**Comment by shrin2024** [comment]
> > all same framework sentences be used such as 'using UnityEngine'. Can gensim ignore these?
> 
> As you mention, `gensim` isn't specialized to code and therefore won't be able to recognize common/utility syntax, e.g. `using UnityEngine`. That being said, if your files are large enough such common parts should not make a big difference.

and sorry, beyond my topic here, I want to know your Github Action workflow no need to clone locally?

**Comment by schunlee** [comment]
> > all same framework sentences be used such as 'using UnityEngine'. Can gensim ignore these?
> 
> As you mention, `gensim` isn't specialized to code and therefore won't be able to recognize common/utility syntax, e.g. `using UnityEngine`. That being said, if your files are large enough such common parts should not make a big difference.

and sorry, beyond my topic here, I want to know your Github Action workflow no need to clone locally?

**Comment by platisd** [comment]
Not sure what you just asked. :grin: 
If you'd like to try it out locally then you'll need to clone install the [dependencies](https://github.com/platisd/duplicate-code-detection-tool?tab=readme-ov-file#dependencies) and follow the [example instructions](https://github.com/platisd/duplicate-code-detection-tool?tab=readme-ov-file#example).

If you'd like to integrate it into your GitHub CI pipelines, then you'll need to set up a workflow as the one described [here](https://github.com/platisd/duplicate-code-detection-tool?tab=readme-ov-file#github-action).

**Comment by schunlee** [comment]
> Not sure what you just asked. 😁 If you'd like to try it out locally then you'll need to clone install the [dependencies](https://github.com/platisd/duplicate-code-detection-tool?tab=readme-ov-file#dependencies) and follow the [example instructions](https://github.com/platisd/duplicate-code-detection-tool?tab=readme-ov-file#example).
> 
> If you'd like to integrate it into your GitHub CI pipelines, then you'll need to set up a workflow as the one described [here](https://github.com/platisd/duplicate-code-detection-tool?tab=readme-ov-file#github-action).

I mean no need checkout step? actually I want to check code across multiple repositories.

**Comment by platisd** [comment]
The action will `checkout` the current branch for you if that's what you are asking. The exact steps can be seen [here](https://github.com/platisd/duplicate-code-detection-tool/blob/master/entrypoint.sh#L16).

**Comment by schunlee** [comment]
> The action will `checkout` the current branch for you if that's what you are asking. The exact steps can be seen [here](https://github.com/platisd/duplicate-code-detection-tool/blob/master/entrypoint.sh#L16).

thanks for your patient and professional.

**Comment by platisd** [comment]
Happy to help. :+1:
